version: '3'

services:
  nginx:
    build: ./nginx
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - web

  web:
    build: .
    command: caldwell
    environment:
      DB_HOST: db
    expose:
      - '3737'
    image: caldwell
    volumes:
      - .:/app
      - box:/box
    depends_on:
      - db
    working_dir: /app

  db:
    image: postgres
    # For linking services.
    expose:
      - '5432'
    # For exposing to host machine.
    # ports:
    #   - 'host:5432'

volumes:
  box:
