version: '3'

services:
  server:
    build: ./nginx
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - app

  app:
    build: .
    command: caldwell
    environment:
      DATABASE_URL: db
    expose:
      - '3737'
    image: caldwell
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    # For linking services.
    expose:
      - '5432'
    # For exposing to host machine.
    # ports:
    #   - 'host:5432'
