version: '3'

services:

  caldwell-api:
    build: .
    image: caldwell-api
    command: caldwell-api
    expose:
      - "1234"
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - caldwell-api
