version: '3'

services:
  server:
    build: ./nginx
    image: nginx
    ports:
      - '8080:80'
    depends_on:
      - app

  app:
    build: .
    command: caldwell
    expose:
      - '1234'
    image: caldwell
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - '5432:5432'
