version: '3'

services:
  nginx:
    build: ./nginx
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - web

  web:
    build: .
    environment:
      DB_HOST: db
    ports:
      - '3737:3737'
    image: caldwell
    volumes:
      - .:/caldwell
    depends_on:
      - db
    working_dir: /caldwell

  db:
    image: postgres
    # For linking services.
    expose:
      - '5432'
    # For exposing to host machine.
    # ports:
    #   - 'host:5432'
