name: caldwell
version: '0.0.1'
category: Web
author: Austin Erlandson
maintainer: austin@erlandson.com
copyright: 2017 Austin Erlandson
license: MIT
github: erlandsona/caldwell-api
extra-source-files:
- README.md

library:
  source-dirs:
    - app/Shared
  ghc-options:
  - -Wall
  - -Werror
  - -ddump-deriv
  - -ddump-splices
  - -fno-warn-orphans
  exposed-modules:
  - Models
  - Routes
  dependencies:
  - base >=4.7 && <5
  - aeson
  - elm-export
  - elm-export-persistent
  - persistent
  - persistent-postgresql
  - persistent-template
  - servant-docs
  - servant-generic
  - servant-server
  - text
  - time
  - turtle

executables:
  caldwell:
    main: Main.hs
    source-dirs: app/Server
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.7 && <5
    - bytestring
    - caldwell
    - monad-logger
    - mtl
    - persistent
    - persistent-postgresql
    - safe
    - servant-generic
    - servant-server
    - transformers
    - wai
    - wai-cors
    - wai-extra
    - warp
  seed:
    main: Seed.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - caldwell
    when:
    - condition: flag(library-only)
      buildable: false

tests:
  caldwell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - caldwell
    - hspec
    - text
    - neat-interpolation
